### ISSUE TITLE
Package needs to be usable with python-wxgtk3.x

### ISSUE THREAD

**Issue by jtlpa** [mrooney/wxbanker#2]
Debian 8 (Jessie), python-wxgtk2.x is not and will not ever be part of Debian 8.
This was at the request of the python-wxgtk developers.

wxBanker needs to be updated to use python-wxgtk3.x

**Comment by jtlpa** [comment]
Please update package so we can continue to use it.

**Comment by xuzhen** [comment]
I committed some fixes to improve the compatibility with wx3.0. https://github.com/mrooney/wxbanker/pull/1
I also built a test package for ubuntu. You can try it on debian.
http://ppa.launchpad.net/xuzhen666/ppa/ubuntu/pool/main/w/wxbanker/wxbanker_0.9.1+git20150818-3_all.deb

**Comment by jtlpa** [comment]
downloaded your source from

http://ppa.launchpad.net/xuzhen666/ppa/ubuntu/pool/main/w/wxbanker/wxbanker_0.9.1+git20150818.orig.tar.xz

extracted and launched using Stans Python Editor (SPE). wxBanker will not run.

Here is the error:
 File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 14453, in Add
return _core_.Sizer_Add(_args, *_kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/common/sizer.cpp(1401) in DoInsert(): too many items (17 > 4*4) in grid sizer (maybe you should omit the number of either rows or columns?)
Script terminated.

Also tried launching from a terminal via python main.py and go the same thing

FYI: OS=Debian 8 Jessie 64bit with Xfce desktop

**Comment by xuzhen** [comment]
The files in that tarball is same as the ones in this git repo without my patches.
You should apply all the patch files in http://ppa.launchpad.net/xuzhen666/ppa/ubuntu/pool/main/w/wxbanker/wxbanker_0.9.1+git20150818-3.debian.tar.xz
